wood/wood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponseNotFound
from django.contrib.auth import views as auth_views
from .views import WoodLogin, WoodRegister, WoodLogout
from django.views.generic.base import TemplateView
from django.http import HttpResponse

from django.views.generic.base import RedirectView


admin.site.site_header = 'wood wide web'
admin.site.site_title = 'wood wide web'
admin.site.index_title = 'Admin'

# def fav(request):
#     return HttpResponseNotFound('no-ico')

urlpatterns = [
    # path('favicon.ico', fav),
    path('favicon.ico', RedirectView.as_view(url='wood_core/static/wood_core/svg/favicon.png')),
    path('robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),

    path('admin/', admin.site.urls),
    
    # path('accounts/', include('django_registration.backends.one_step.urls')),
    path('<lang>/accounts/registration/', WoodRegister.as_view(), name='registration'),

    path('register/closed/',
        TemplateView.as_view(
            template_name='django_registration/registration_closed.html'
        ),
        name='django_registration_disallowed'),
    path('register/complete/',
        TemplateView.as_view(
            template_name='django_registration/registration_complete.html'
        ),
        name='django_registration_complete'),


    path('<lang>/accounts/login/', WoodLogin.as_view(), name='login'),
    path('<lang>/accounts/logout/', WoodLogout.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path('', include('wood_core.urls')),
    path('', include('wood_walk.urls')),

    path('lingua/', include('wood_lingua.urls')),
]

wood/wood_core/urls.py
from django.urls import path, include

from wood_core.views import (
    atlas_data,
    atlas_page,
    # atlas_page_contrib,
    atlas_map,
    media,
    media_site,
    about_page,
    front_page,
    list_all_trees,
    add_tree,
    edit_tree,
    # contribution_new,
    # contribution_edit,
    text_contribution_new,
    text_contribution_edit,
    text_delete_validation,
    text_contribution_delete,
    img_contribution_new,
    img_contribution_edit,
    img_contribution_delete,
    img_delete_validation,

    contribution_list,
    focus,
    # get_contrib_data,
    walks_1050
)

urlpatterns = [
    path('media-site/<name>/<int:target>', media_site, name='wood-media-site'),
    path('media/<model>/<int:id>/<int:target>', media, name='wood-media'),
    path('atlas/data/', atlas_data, name='wood-data'),
    # path('adopte/<cid>', get_contrib_data, name='wood-adopte'),
    path('<lang>/focus/<tid>', focus, name='wood-focus'),
    path('<lang>/sitemap', list_all_trees, name='list-all-trees'),

    path('<lang>/add/new', add_tree, name = 'wood-add-tree'),
    path('<lang>/edit/<int:id>', edit_tree, name = 'wood-edit-tree'),
    # path('<lang>/contrib/<int:tid>/new', contribution_new, name='wood-contrib-new'),
    # path('<lang>/contrib/edit/<int:id>',contribution_edit, name='wood-contrib-edit'),

    path('<lang>/textcontrib/<int:tid>/new', text_contribution_new, name='wood-text-contrib-new'),
    path('<lang>/textcontrib/<int:tid>/edit/<int:id>',text_contribution_edit,name='wood-text-contrib-edit'),
    path('<lang>/textcontrib/deletevalidation/<int:id>', text_delete_validation, name="wood-text-del-valid"),
    path('<lang>/textcontrib/delete/<int:id>', text_contribution_delete, name='wood-text-contrib-del'),

    path('<lang>/imgcontrib/<int:tid>/edit/<int:id>',img_contribution_edit,name='wood-img-contrib-edit'),
    path('<lang>/imgcontrib/<int:tid>/new', img_contribution_new, name='wood-img-contrib-new'),
    path('<lang>/imgcontrib/deletevalidation/<int:id>', img_delete_validation, name="wood-img-del-valid"),
    path('<lang>/imgcontrib/delete/<int:id>', img_contribution_delete, name='wood-img-contrib-del'),

    path('<lang>/contrib/', contribution_list, name='wood-contrib'),
    path('<lang>/atlas.html', atlas_map, name='wood-atlas'),
    path(
        '<lang>/atlas/id_<pid>.html',
        atlas_page,
        name='wood-atlas-tree-imported'),
    path('<lang>/atlas/<int:pid>.html', atlas_page, name='wood-atlas-tree'),
    path('1050/<lang>/', walks_1050, name='wood-walks-1050'),
    # path(
    #     '<lang>/atlas/contrib/<int:cid>.html',
    #     atlas_page_contrib,
    #     name='wood-atlas-tree-contrib'),
    path('<lang>/about.html', about_page, name='wood-about'),
    path('<lang>/index.html', front_page, name='wood-index'),
    path('<lang>/', front_page),
]

wood/wood_core/models/subject.py
#  Copyright (C) 2018 Atelier Cartographique <contact@atelier-cartographique.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from urllib.request import Request
from datetime import datetime, timezone
from django.contrib.gis.db import models
from django.conf import settings
from easy_thumbnails.fields import ThumbnailerImageField

from wood_core.fields import PointField
from wood_lingua.models import message_field
from wood_botanique.models.species import Taxon

from .media import picture, slugify
from .ancillary import BaseLink
from .service import TreeService


class TreeManager(models.Manager):
    def get_queryset(self):
        select = (
            'name',
            'description',
            'street_address',
            'city',
            'post_code',
        )
        return super().get_queryset().select_related(*select)


def upload_to_photomaton(instance, fn):
    id = instance.id
    return 'phototomaton/{}/{}'.format(id, slugify(fn))


class Tree(models.Model):
    """Models a general Tree (from inventory, contribution, ...)
    """
    objects = TreeManager()

    REMARQUABLE = 'rmqb'
    REMARQUE = 'rmqe'
    ADOPTE = 'adpt'
    PLANTE = 'plnt'
    INVENTAIRE = 'inv'
    CONTRIBUE = 'ctrb'
    CATEGORY = (
        (REMARQUABLE, 'Remarquable'),
        (REMARQUE, 'Remarqué'),
        (ADOPTE, 'Adopté'),
        (PLANTE, 'Planté'),
        (INVENTAIRE, 'Inventaire'),
        (CONTRIBUE, 'Contribué'),
    )

    id = models.AutoField(primary_key=True)
    patrimoine = models.IntegerField(blank=True, null=True)
    import_id = models.CharField(max_length=12, null=True, blank=True)
    category = models.CharField(
        max_length=4, choices=CATEGORY, null=True, blank=True)
    taxon = models.ForeignKey(
        Taxon, on_delete=models.CASCADE, null=True, blank=True)

    photomaton = ThumbnailerImageField(
        upload_to=upload_to_photomaton, null=True, blank=True)

    name = message_field('tree_name', null=True, blank=True)
    description = message_field('tree_description', null=True, blank=True)

    street_address = message_field(
        'tree_street_address', null=True, blank=True)
    city = message_field('tree_city', null=True, blank=True)
    post_code = message_field('tree_post_code', null=True, blank=True)
    position = PointField(srid=4326, null=True, blank=True)

    height = message_field('tree_height', null=True, blank=True)
    circumference = message_field('tree_circumference', null=True, blank=True)
    crown_diameter = message_field(
        'tree_crown_diameter', null=True, blank=True)

    service = models.ForeignKey(
        TreeService, on_delete=models.CASCADE, null=True, blank=True)

    #item caract
    source = models.CharField(max_length=64, null=True, blank=True)
    date = models.DateTimeField(auto_now=True, null=True, blank=True)

    # from contribution
    validated = models.BooleanField(default=False)
    contributor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True, blank=True,
    )

    def get_highlights(self):
        now = datetime.now(timezone.utc)
        return self.highlight_set.filter(start__lte=now, end__gte=now)

    def is_highlighted(self):
        return self.get_highlights().count() > 0

    def __str__(self):
        if self.name:
            return '{} ({})'.format(self.name, self.id)
        elif self.taxon:
            return '{} ({})'.format(self.taxon.name, self.id)
        return 'Tree ({})'.format(self.id)


TreePicture = picture(Tree, is_sorted=True)


class Remarqueur(BaseLink):
    url = message_field('remarqueur_url')
    label = message_field('remarqueur_label')


class Activity(BaseLink):
    url = message_field('activity_url')
    label = message_field('activity_label')


class LinkedMedia(BaseLink):
    url = models.URLField(null=True, blank=True)
    url_lingua = message_field('media_url', null=True, blank= True)
    label = message_field('linked_media_label')

    def get_url(self, lang):
        if self.url_lingua is not None:
            url_new =  getattr(self.url_lingua, lang)
            try:
                Request(url_new)
            except ValueError:
                return 'missing URL in {} for linked media {}'.format(lang, self.id)
            return url_new
        return self.url

class Jumelage(BaseLink):
    BELGIQUE = 'belgique'
    EUROPE = 'europe'
    MONDE = 'monde'
    SCOPE = (
        (BELGIQUE, 'Belgique'),
        (EUROPE, 'Europe'),
        (MONDE, 'Monde'),
    )
    scope = models.CharField(max_length=12, choices=SCOPE)

    url = models.URLField(null=True, blank=True)
    url_lingua = message_field('jumelage_url', null=True, blank= True)
    label = message_field('jumelage_label')

    def get_url(self, lang):
        if self.url_lingua is not None:
            url_new =  getattr(self.url_lingua, lang)
            try:
                Request(url_new)
            except ValueError:
                return 'missing URL in {} for twin {}'.format(lang, self.id)
            return url_new
        return self.url

wood/wood_core/views/common.py
from pathlib import Path

from django.shortcuts import  get_object_or_404,  redirect
from django.http import (
    FileResponse,
    Http404,
    )
from django.urls import reverse
from django.conf import settings
from pyproj import CRS, Transformer
from easy_thumbnails.files import  Thumbnailer
from django.contrib.auth.views import redirect_to_login

from wood_botanique.models.species import TaxonPicture

from wood_core.models.subject import Tree, TreePicture
from wood_core.models.contrib import  PictureContrib,  ImageContribution

from wood_walk.models import  WalkEdge

wgs = CRS('EPSG:4326')
lambert72 = CRS('EPSG:31370')
transformer = Transformer.from_crs(wgs, lambert72)

def login_required_lingua(next_name):
# next_name is the name of the next page to redirect to after login.

    def dec(fn):
        def inner(request, lang, *args, **kwargs):
            u = request.user
            if u.is_authenticated:
                return fn(request, lang, *args, **kwargs)
            
            # if there are other arguments than the langage, like the tree-id, use it in the reverse function
            reverse_args = [lang,] + list(kwargs.values())
            return  redirect_to_login(
                reverse(next_name, args=reverse_args) , 
                reverse('login', args=(lang,)),)
        
        return inner
    return dec

def get_size(w, h, target):
    if w > h:
        r = target / w
    else:
        r = target / h
    tw = w * r
    th = h * r
    return (tw, th)

def media(request, model, id, target):
    if 'treepicture' == model:
        obj = get_object_or_404(TreePicture, pk=id)
        width, height = get_size(obj.file.width, obj.file.height, target)
        thumb = obj.file.get_thumbnail({'size': [width, height]})
        return redirect(thumb.url, permanent=True)
    elif 'tree' == model:
        obj = get_object_or_404(Tree, pk=id)

        # if obj.photomaton is not None:
        photomaton = obj.photomaton
        # elif obj.category == 'ctrb':
        #     imgcontribs = ImageContribution.objects.filter(tree_id=id)
        #     photomaton = imgcontribs[0].picture            
        
        if photomaton is None:
            raise Http404('This contrib does not have any image Yet!')
        
        width, height = get_size(photomaton.width, photomaton.height, target)
        thumb = photomaton.get_thumbnail({'size': [width, height]})
        return redirect(thumb.url, permanent=True)
    elif 'taxon' == model:
        obj = get_object_or_404(TaxonPicture, pk=id)
        width, height = get_size(obj.file.width, obj.file.height, target)
        thumb = obj.file.get_thumbnail({'size': [width, height]})
        return redirect(thumb.url, permanent=True)
    elif 'contrib' == model:
        # obj = get_object_or_404(Contribution, pk=id)
        obj = get_object_or_404(Tree, pk=id)
        imgcontribs = ImageContribution.objects.filter(tree_id=id)
        contrib = imgcontribs[0].picture
        if contrib is None:
            raise Http404('This contrib does not have any image Yet!')
        thumb = contrib.image.get_thumbnail(
            {
                'size': [target, target],
            },
            generate=True,
            save=True,
        )
        thumb.seek(0)
        return FileResponse(thumb)
    elif 'img-contrib' == model:
        obj = get_object_or_404(ImageContribution, pk=id)
        thumb = obj.picture.get_thumbnail(
            {
                'size':[target, target],
            },
            generate=True,
            save=True,
        )
        thumb.seek(0)
        return FileResponse(thumb)
    
    elif 'contrib-extra' == model:
        obj = get_object_or_404(PictureContrib, pk=id)
        thumb = obj.file.get_thumbnail(
            {
                'size': [target, target],
            },
            generate=True,
            save=True,
        )
        thumb.seek(0)
        return FileResponse(thumb)
    elif 'walkedge' == model:
        obj = get_object_or_404(WalkEdge, pk = id)
        thumb = obj.image.get_thumbnail(
            {
                'size': [target, target],
            },
            generate=True,
            save=True,
        )
        thumb.seek(0)
        return FileResponse(thumb)


def media_site(request, name, target):
    static_root = Path(getattr(settings, 'STATIC_ROOT'))
    img_path = static_root.joinpath('wood_core/images', name)
    with open(img_path.as_posix(), 'rb') as f:
        thumbnailer = Thumbnailer(f, img_path.stem)
        thumb = thumbnailer.get_thumbnail({'size': [target, target]})
        return redirect(thumb.url, permanent=True)

wood/wood_core/views/home.py
from django.shortcuts import render

from wood_core.models.subject import Tree, TreePicture, Remarqueur
from wood_core.models.ancillary import Portrait


def front_page(request, lang):
    """Serve the landing page
    """
    template_name = 'wood_core/site-{}/index.html'.format(lang)
    tree_count = Tree.objects.count()
    # contrib_count = Contribution.objects.filter(validated=True).count()
    context = {
        'lang': lang,
        'counter': tree_count,
        'monthly': Portrait.objects.filter(monthly=True).first()
    }
    return render(request, template_name, context)


def about_page(request, lang):
    """Serve the landing page
    """
    template_name = 'wood_core/site-{}/about.html'.format(lang)

    actors_dict = dict()

    for r in Remarqueur.objects.all():
        try:
            lid = getattr(r.label, lang)
            if lid not in actors_dict:
                actors_dict[lid] = dict(name=lid, url=r.url, trees=[])
            actors_dict[lid]['trees'].append(r.tree)
        except Exception:
            pass

    actors = sorted([s for s in actors_dict.values()],
                    key=lambda x: x['name'].lower())

    context = dict(lang=lang, actors=actors)
    return render(request, template_name, context)

def list_all_trees(request, lang):
    """List all the trees, for referencing
    """
    template_name = 'wood_core/site_map.html'
    trees = Tree.objects.all()

    context = dict(
        lang=lang,
        trees = trees,
    )

    return render(request, template_name, context)

wood/wood_core/views/walks.py
from django.shortcuts import render

def walks_1050(request, lang):
    """Link to Ixelles walks and other activities
    """

    template_name = 'wood_core/index-1050.html'
    context = {
        'lang':lang
    }

    return render(request, template_name, context)

wood/wood_core/templates/wood_core/about-block3.html
{% load static %}
{% load wood %}


<article class="how-to">

    <div class="ba-wrapper">

        <div class="ba-txt-wrapper">

            <div class="pitch black">
                <span>{% tr_label lang fr="Utiliser" nl="De atlas" en="" %}</span>
                <span>{% tr_label lang fr="l'atlas" nl="gebruiken" en="" %}</span>
            </div>

            <div class="sub-pitch black">

                {% if lang == 'fr' %}
                <a href="{% static 'wood_core/files/Page_APropos1a1_Atlas.pdf' %}">Lire la documentation</a>
                {% elif lang == 'nl' %}
                <a href="{% static 'wood_core/files/Page_APropos1a1_Atlas_NL.pdf' %}">Lees hier de info</a>
                {% else %}
                <a href="{% static 'wood_core/files/Page_APropos1a1_Atlas.pdf' %}">Read more</a>
                {% endif %}

            </div>
        </div>
    </div>

    <div class="ba-wrapper">

        <div class="ba-txt-wrapper">

            <div class="pitch orange">
                <span>{% tr_label lang fr="Fiches" nl="Fiches" en="" %}</span>
                <span>{% tr_label lang fr="et portraits" nl="en portretten" en="" %}</span>
            </div>

            <div class="sub-pitch black">{% tr_label lang fr="Chacun des points de la carte mène à une fiche ou un grand portrait qui dévoilent l'identité d'un arbre, son rôle, et son caractère." nl="Iedere stip op de kaart leidt naar een fiche of een uitgebreid portret over de identiteit van de boom, zijn rol en zijn karakter" en="" %} 
                <br>
                <br>

                {% if lang == 'fr' %}
                <a href="{% static 'wood_core/files/Page_APropos1a2_FichePortrait.pdf' %}">Lire la documentation</a> <br>
                <a href="{% static 'wood_core/files/Bibliographie_et_Webographie.pdf' %}">Bibliographie</a>
                {% elif lang == 'nl' %}
                <a href="{%static 'wood_core/files/Page_APropos1a2_FichePortrait_NL.pdf' %}">Lees hier de info</a>
                {% else %}
                <a href="{% static 'wood_core/files/Page_APropos1a2_FichePortrait.pdf' %}">Read more</a>
                {% endif %}

            </div>
        </div>
    </div>

    <div class="ba-wrapper">

        <div class="ba-txt-wrapper">

            <div class="pitch green">
                <span>{% tr_label lang fr="Services" nl="Nut" en="" %}</span>
                <span>{% tr_label lang fr="de l'arbre" nl="van de boom" en="" %}</span>
            </div>

            <div class="sub-pitch black">{% tr_label lang fr="Pourquoi les arbres sont-ils essentiels en ville ? <br> En quoi sont-ils intéressants pour nous et pour le milieu urbain ?" nl="Waarom zijn bomen onmisbaar in de stad? Welk belang hebben ze voor ons en voor de stadsomgeving?" en="" %} <br>
            <br>

            {% if lang == 'fr' %}
            <a href="{% static 'wood_core/files/Page_APropos1a3_ArbreUtile.pdf' %}">Lire la documentation</a>
            {% elif lang == 'nl' %}
            <a href="{% static 'wood_core/files/Page_APropos1a3_ArbreUtile_NL.pdf' %}">Lees hier de info</a>
            {% else %}
            <a href="{% static 'wood_core/files/Page_APropos1a3_ArbreUtile.pdf' %}">Read more</a>
            {% endif %}

            </div>
        </div>
    </div>
</article>

wood/wood_core/templates/wood_core/about-block6.html
{% load static %}
{% load wood %}

<article class="actors-img">

    <div class="pitch white">
    {% comment %} {% tr_label lang fr="La communauté : <br> les acteurs de la forêt" nl="De gemeenschap: <br> de spelers van het bos" en="The community : Actors in the forest" %} {% endcomment %}
    {% tr_label lang fr="La communauté:" nl="De gemeenschap:" en="The community:" %}
    </div>

    <div class="sub-pitch white">
        {% tr_label lang fr="Merci aux arbres et à la forêt, ces êtres vivants <br> sensibles, communicants, complexes, silencieux, incroyablement efficaces, <br> qui nous inspirent et qui nous rendent tant de services essentiels." nl='Bedankt aan de bomen en het bos, die gevoelige, <br> complexe, stille, ongelooflijk efficiënte levende wezens, <br> die met elkaar in verbinding staan, die ons inspireren  <br> en die ons zoveel essentiële diensten verlenen.' en='Thank you to the trees and the forest. <br> These sensitive, communicative, complex, silent, <br> and incredibly efficient living beings which inspire us <br> and help us with so many essential things in life.' %}
    </div>
    <div class="sub-pitch white">
        {% tr_label lang fr="Merci aussi à tous ceux et celles qui s’impliquent,  <br> ponctuellement, ou régulièrement dans Wood Wide Web." nl='Bedankt ook aan iedereen die sporadisch <br> of regelmatig betrokken is bij Wood Wide Web.' en='Thank you as well to everyone that gets involved, <br> whether regularly or occasionally, with Wood Wide Web.' %}
    </div>
</article>

wood/wood_core/templates/wood_core/bota.html
{% load wood %}
<div class="planche-bota-wrapper">
{% for picture in tree.taxon.picture_taxon.all %}
    <a href="{{ picture.file.url }}">
        <img src="{% url 'wood-media' 'taxon' picture.id 600 %}" alt="">
    </a>
    {% if picture.caption|tr:lang is not '' %}
    <div class="caption">
        {{ picture.caption|tr:lang }}
    </div>
    {% endif %} 
{% endfor %}
</div>

wood/wood_core/templates/wood_core/index-block9.html
{% load static %}
{% load wood %}

<article class="portrait" id = "block9">

    <div class="portrait-wrapper">

        <div class="portrait-textwrapper">

            <div class="pitch green"> 
                {% tr_label lang fr="Des portraits <br> multimédia racontent <br> l’histoire d’arbres <br> monumentaux" nl="Multimedia-portretten <br> vertellen het verhaal <br> van monumentale bomen"  en="Multimedia portraits <br> tell the stories <br> of monumental trees" %}
            </div>

            <div class="sub-pitch black"> 
                {% if lang == 'fr' %}
                Une série de fiches <a href="{% static 'wood_core/files/Article_Fiches_et_Portraits_FR.pdf' %}" target="_blank">pédagogiques</a>
                <br> 
                caractérisent certains arbres <br> remarquables
                {% elif lang == 'nl' %}
                Serie <a href="{% static 'wood_core/files/Article_Fiches_et_Portraits_NL.pdf' %}" target="_blank">Leerrijke</a> fiches <br> schetsen een beeld van <br> opmerkelijke bomen
                {% else %}
                A series of original botanical illustrations and <a href="{% static 'wood_core/files/Article_Fiches_et_Portraits_FR.pdf' %}" target="_blank">educational files</a>
                    <br> all about certain notable trees
                {% endif %}
                
                </div>
        </div>

        <div class="illu-fiches-fr"></div>
    </div>

    <div class="arrow-down">
        <a href= "#footer"><img src="{% static 'wood_core/svg/arrow-down-black.svg' %}" alt=""></a>
        </div>
</article>

wood/wood_core/templates/wood_core/linked-medias.html
{% load wood %}

<!-- linked-medias -->
{% if tree.linkedmedia_set.count > 0 %}
    <div class="linked-medias">
        <h2>{% tr_label lang fr="Médias liés" nl="Gerelateerde media" en="Related media" %}</h2>
        {% for linked_media in tree.linkedmedia_set.all %}
            
            <li><a 
            href="{{linked_media|lingua_url:lang}}"
            title="{{linked_media|lingua_url:lang}}" 
            target="_blank"
            >{{ linked_media.label|tr:lang }}</a></li>

        {% endfor %}

    </div>
{% endif %}

wood/wood_core/templates/wood_core/situation.html
{% load wood %}

<!-- address -->

<div class="address">

    {% if tree.street_adress or tree.city %}
    <div class="item">

        <div class="label">{% tr_label lang fr="Adresse :" nl="Adres :" en='Adress' %}</div>

        <div class="content">
            <span>{{ tree.street_address|tr:lang }}</span>
            <span> </span>
            <span>{{ tree.city|tr:lang }}</span>
        </div>
    </div>
    {% endif %}

    <div class="item">
        <div class="label">{% tr_label lang fr="Coordonnées GPS :" nl="Gps-coörd. :" en="GPS coordinates : " %}</div>

        <div class="content">
            <span>{{ tree.position.coords.1 |floatformat:4 }}</span>
            <span>, {{ tree.position.coords.0 |floatformat:4 }}</span>
        </div>
    </div>

    {% if tree.patrimoine %}
    <div class="item">

        <div class="label">
            {% tr_label lang fr="Inventaire scientifique :" nl="Wetenschappelijke inventarisatie :" en='Scientific inventory' %}
        </div>

        <div class="content">
            <span><a
                    href="http://{% tr_label lang fr="arbres-inventaire" nl="bomen-inventaris" en="arbres-inventaire" %}.irisnet.be/tree.php?id={{tree.patrimoine}}/" target="_blank">{{tree.patrimoine}}</a></span>
        </div>
    </div>
    {% endif %}

    {% if tree.category == 'rmqe' %}
    <div class="item">

        <div class="label">{% tr_label lang fr="Partenaire :" nl="Partner :" en="Partner :" %}</div>

        <div class="content">
            <span>{% tr_label lang fr="Cet arbre a été ajouté à l’atlas de Wood Wide Web par" nl="Deze boom is toegevoegd aan de Wood Wide Web atlas door" en="This tree has been added to the WoodWideWeb atlas by "%}</span>
            <span> </span> {% for r in tree.remarqueur_set.all %} {% if r.url|tr:lang is not '' %} <span> <a
                    href="{{ r.url|tr:lang }}" target="_blank">{{ r.label|tr:lang }}</a> </span> {% else %}
            <span>{{ r.label|tr:lang }}</span> {% endif %} {% endfor %} </div>
    </div>
    {% endif %}

    {% if tree.contributor or tree.contributions.first %}
    <div class="item">

        <div class="label">{% tr_label lang fr="Contributeurs :" nl="Inzenders :" en="Contributors :" %}</div>

        <div class="content">
            {% for contributor in contributors %}
            {% if forloop.last %}
            <span>{{ contributor.get_username }}</span>
            {% else %}
            <span>{{ contributor.get_username }},</span>
            {% endif %}
            {% endfor %}

        </div>
    </div>
    {% endif %}

    

    {% comment " Not implemented" %} <div class="item">

        <div class="label">Coordonnées Lambert :</div>

        <div class="content">
            <span>{{ LAMBERT_1 }}</span>
            <span>, {{ LAMBERT_2 }}</span>
        </div>
    </div> {% endcomment %}
</div>

wood/wood_core/templates/wood_core/title.html
{% load wood %}

<!-- BLOCK TITLE -->

<div class="block-title">
    <h1>
        {% tree_name lang tree %} <br>
        {% tree_sub_title lang tree %}

        <!-- {{ tree.street_address|tr:lang }} -->
    </h1>
</div>

wood/wood_core/templates/wood_core/walk.html
{% load wood %}
{% for walk_in in tree.walk_in_node.all %}
<a href="{% url 'wood-walk-single' lang walk_in.walk.id %}">
    {{ walk_in.walk.title|tr:lang }}
</a>
{% endfor %}